set(_CATKIN_CURRENT_PACKAGE "ekf_localization")
set(ekf_localization_VERSION "0.0.0")
set(ekf_localization_MAINTAINER "agrotech <agrotech@todo.todo>")
set(ekf_localization_PACKAGE_FORMAT "2")
set(ekf_localization_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf2" "tf2_geometry_msgs" "tf2_ros")
set(ekf_localization_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf2" "tf2_geometry_msgs" "tf2_ros")
set(ekf_localization_BUILDTOOL_DEPENDS "catkin")
set(ekf_localization_BUILDTOOL_EXPORT_DEPENDS )
set(ekf_localization_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf2" "tf2_geometry_msgs" "tf2_ros")
set(ekf_localization_RUN_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf2" "tf2_geometry_msgs" "tf2_ros")
set(ekf_localization_TEST_DEPENDS )
set(ekf_localization_DOC_DEPENDS )
set(ekf_localization_URL_WEBSITE "")
set(ekf_localization_URL_BUGTRACKER "")
set(ekf_localization_URL_REPOSITORY "")
set(ekf_localization_DEPRECATED "")